name: Backend_Safety_Check

on: [push, pull_request]

jobs:
  check-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: Backend
        run: npm install

      - name: Backend Syntax Check
        working-directory: Backend
        # Ye command sirf check karegi ki code sahi hai ya nahi
        run: node --check src/app.js

  check-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend
        working-directory: Frontend
        run: npm install

      - name: Build Check
        working-directory: Frontend
        run: npm run build